[package]
name = "chip8-rust"
version = "0.1.0"
edition = "2021"
publish = false

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
pixels = "0.9.0"
winit = "0.26.0"
winit_input_helper = "0.11.0"
